// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clips.sql

package dblayer

import (
	"context"
	"database/sql"
)

const createClip = `-- name: CreateClip :exec
INSERT INTO clips(userid, text) VALUES (
    ?, ?
)
`

type CreateClipParams struct {
	Userid int64
	Text   sql.NullString
}

func (q *Queries) CreateClip(ctx context.Context, arg CreateClipParams) error {
	_, err := q.db.ExecContext(ctx, createClip, arg.Userid, arg.Text)
	return err
}

const deleteClip = `-- name: DeleteClip :exec
DELETE FROM clips
    WHERE userid = ?
`

func (q *Queries) DeleteClip(ctx context.Context, userid int64) error {
	_, err := q.db.ExecContext(ctx, deleteClip, userid)
	return err
}

const getClipContent = `-- name: GetClipContent :one
SELECT text FROM clips
    WHERE id = ?
`

func (q *Queries) GetClipContent(ctx context.Context, id int64) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getClipContent, id)
	var text sql.NullString
	err := row.Scan(&text)
	return text, err
}

const updateClip = `-- name: UpdateClip :exec
UPDATE clips
    SET text = ?
WHERE userid = ?
`

type UpdateClipParams struct {
	Text   sql.NullString
	Userid int64
}

func (q *Queries) UpdateClip(ctx context.Context, arg UpdateClipParams) error {
	_, err := q.db.ExecContext(ctx, updateClip, arg.Text, arg.Userid)
	return err
}
