// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: csrf.sql

package dblayer

import (
	"context"
)

const createCSRFToken = `-- name: CreateCSRFToken :exec
INSERT INTO csrf(userid, token) VALUES (
    ?, ?
)
`

type CreateCSRFTokenParams struct {
	Userid int64
	Token  string
}

func (q *Queries) CreateCSRFToken(ctx context.Context, arg CreateCSRFTokenParams) error {
	_, err := q.db.ExecContext(ctx, createCSRFToken, arg.Userid, arg.Token)
	return err
}

const deleteCSRFToken = `-- name: DeleteCSRFToken :exec
DELETE FROM csrf
    WHERE userid = ?
`

func (q *Queries) DeleteCSRFToken(ctx context.Context, userid int64) error {
	_, err := q.db.ExecContext(ctx, deleteCSRFToken, userid)
	return err
}

const getCSRFToken = `-- name: GetCSRFToken :one
SELECT id, userid, token, expiry FROM csrf
    WHERE userid = ?
`

func (q *Queries) GetCSRFToken(ctx context.Context, userid int64) (Csrf, error) {
	row := q.db.QueryRowContext(ctx, getCSRFToken, userid)
	var i Csrf
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Token,
		&i.Expiry,
	)
	return i, err
}

const renewCSRFToken = `-- name: RenewCSRFToken :exec
UPDATE csrf
SET
    token = ?,
    expiry = ?
WHERE userid = ?
`

type RenewCSRFTokenParams struct {
	Token  string
	Expiry string
	Userid int64
}

func (q *Queries) RenewCSRFToken(ctx context.Context, arg RenewCSRFTokenParams) error {
	_, err := q.db.ExecContext(ctx, renewCSRFToken, arg.Token, arg.Expiry, arg.Userid)
	return err
}

const verifyCSRFToken = `-- name: VerifyCSRFToken :one
SELECT EXISTS (
    SELECT id
    FROM csrf
WHERE token = ?
)
`

func (q *Queries) VerifyCSRFToken(ctx context.Context, token string) (int64, error) {
	row := q.db.QueryRowContext(ctx, verifyCSRFToken, token)
	var id int64
	err := row.Scan(&id)
	return id, err
}
