// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dblayer

import (
	"database/sql"
)

type Clip struct {
	ID      int64
	Userid  int64
	Text    sql.NullString
	Expires sql.NullString
}

type Csrf struct {
	ID     int64
	Userid int64
	Token  string
	Expiry string
}

type Paste struct {
	ID      int64
	Userid  int64
	Text    sql.NullString
	Expires sql.NullString
}

type Session struct {
	ID     int64
	Userid int64
	Token  string
	Expiry string
}

type User struct {
	ID       int64
	Username string
	Password string
}
