// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dblayer

import (
	"database/sql"
)

type Clip struct {
	ID     int64
	Userid int64
	Text   sql.NullString
}

type Paste struct {
	ID     int64
	Userid int64
	Text   sql.NullString
}

type User struct {
	ID       int64
	Username string
	Password string
}
