// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pastes.sql

package dblayer

import (
	"context"
)

const createPaste = `-- name: CreatePaste :exec
INSERT INTO pastes(userid, text, expires) VALUES (
    ?, ?, ?
)
`

type CreatePasteParams struct {
	Userid  int64
	Text    string
	Expires string
}

func (q *Queries) CreatePaste(ctx context.Context, arg CreatePasteParams) error {
	_, err := q.db.ExecContext(ctx, createPaste, arg.Userid, arg.Text, arg.Expires)
	return err
}

const deleteAllPastesFromUser = `-- name: DeleteAllPastesFromUser :exec
DELETE FROM pastes
    WHERE userid = ? AND expires > CURRENT_TIMESTAMP
`

func (q *Queries) DeleteAllPastesFromUser(ctx context.Context, userid int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllPastesFromUser, userid)
	return err
}

const deletePaste = `-- name: DeletePaste :one
DELETE FROM pastes
    WHERE id = ?
    AND expires > CURRENT_TIMESTAMP
RETURNING id
`

func (q *Queries) DeletePaste(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, deletePaste, id)
	err := row.Scan(&id)
	return id, err
}

const getAllPastes = `-- name: GetAllPastes :many
SELECT id, userid, text, expires FROM pastes
    WHERE
        userid = ?
        AND
        expires > CURRENT_TIMESTAMP
`

func (q *Queries) GetAllPastes(ctx context.Context, userid int64) ([]Paste, error) {
	rows, err := q.db.QueryContext(ctx, getAllPastes, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Paste
	for rows.Next() {
		var i Paste
		if err := rows.Scan(
			&i.ID,
			&i.Userid,
			&i.Text,
			&i.Expires,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaste = `-- name: UpdatePaste :one
UPDATE pastes
    SET text = ?
WHERE id = ?
AND
expires > CURRENT_TIMESTAMP
RETURNING id
`

type UpdatePasteParams struct {
	Text string
	ID   int64
}

func (q *Queries) UpdatePaste(ctx context.Context, arg UpdatePasteParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updatePaste, arg.Text, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
