// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pastes.sql

package dblayer

import (
	"context"
	"database/sql"
)

const createPaste = `-- name: CreatePaste :exec
INSERT INTO pastes(userid, text) VALUES (
    ?, ?
)
`

type CreatePasteParams struct {
	Userid int64
	Text   sql.NullString
}

func (q *Queries) CreatePaste(ctx context.Context, arg CreatePasteParams) error {
	_, err := q.db.ExecContext(ctx, createPaste, arg.Userid, arg.Text)
	return err
}

const deleteAllClipsFromUser = `-- name: DeleteAllClipsFromUser :exec
DELETE FROM pastes
    WHERE userid = ?
`

func (q *Queries) DeleteAllClipsFromUser(ctx context.Context, userid int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllClipsFromUser, userid)
	return err
}

const deletePaste = `-- name: DeletePaste :exec
DELETE FROM pastes
    WHERE id = ?
`

func (q *Queries) DeletePaste(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePaste, id)
	return err
}

const getAllPastes = `-- name: GetAllPastes :many
SELECT id, userid, text, expires FROM pastes
    WHERE userid = ?
`

func (q *Queries) GetAllPastes(ctx context.Context, userid int64) ([]Paste, error) {
	rows, err := q.db.QueryContext(ctx, getAllPastes, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Paste
	for rows.Next() {
		var i Paste
		if err := rows.Scan(
			&i.ID,
			&i.Userid,
			&i.Text,
			&i.Expires,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaste = `-- name: UpdatePaste :exec
UPDATE pastes
    SET text = ?
WHERE id = ?
`

type UpdatePasteParams struct {
	Text sql.NullString
	ID   int64
}

func (q *Queries) UpdatePaste(ctx context.Context, arg UpdatePasteParams) error {
	_, err := q.db.ExecContext(ctx, updatePaste, arg.Text, arg.ID)
	return err
}
