// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package dblayer

import (
	"context"
)

const createSessionToken = `-- name: CreateSessionToken :exec
INSERT INTO session(userid, token) VALUES (
    ?, ?
)
`

type CreateSessionTokenParams struct {
	Userid int64
	Token  string
}

func (q *Queries) CreateSessionToken(ctx context.Context, arg CreateSessionTokenParams) error {
	_, err := q.db.ExecContext(ctx, createSessionToken, arg.Userid, arg.Token)
	return err
}

const deleteSessionToken = `-- name: DeleteSessionToken :exec
DELETE FROM session
    WHERE userid = ?
`

func (q *Queries) DeleteSessionToken(ctx context.Context, userid int64) error {
	_, err := q.db.ExecContext(ctx, deleteSessionToken, userid)
	return err
}

const getSessionToken = `-- name: GetSessionToken :one
SELECT id, userid, token, expiry FROM session
    WHERE userid = ?
`

func (q *Queries) GetSessionToken(ctx context.Context, userid int64) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionToken, userid)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Token,
		&i.Expiry,
	)
	return i, err
}

const getUserIDFromSessionToken = `-- name: GetUserIDFromSessionToken :one
SELECT userid FROM session
    WHERE token = ?
`

func (q *Queries) GetUserIDFromSessionToken(ctx context.Context, token string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserIDFromSessionToken, token)
	var userid int64
	err := row.Scan(&userid)
	return userid, err
}

const renewSessionToken = `-- name: RenewSessionToken :exec
UPDATE session
SET
    token = ?,
    expiry = ?
WHERE userid = ?
`

type RenewSessionTokenParams struct {
	Token  string
	Expiry string
	Userid int64
}

func (q *Queries) RenewSessionToken(ctx context.Context, arg RenewSessionTokenParams) error {
	_, err := q.db.ExecContext(ctx, renewSessionToken, arg.Token, arg.Expiry, arg.Userid)
	return err
}
