CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS clips (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userid INTEGER UNIQUE NOT NULL,
    text TEXT,
    FOREIGN KEY (userid) REFERENCES users(id)
)

CREATE TABLE pastes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userid INTEGER NOT NULL,
    text TEXT,
    FOREIGN KEY (userid) REFERENCES users(id)
)
